export const defaultValue = {
    age: {
        value: 0,
        initialValue: 0,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Age",
        min: '0',
        max: '100',
        placeholder: "0",
        description: "The patient's age",
    },
    psa: {
        value: 0,
        initialValue: 0,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "PSA",
        min: '0',
        max: '10000',
        placeholder: "0",
        description: "The latest PSA score: this ranges from 0-10,000",
    },
    clinicalStage: {
        value: 'T1c',
        initialValue: '',
        type: "select",
        options: ['T1c', 'T1', 'T2a', 'T2b', 'T2c', 'T3a', 'T3b', 'T4', 'N', 'M'],
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Clinical Stage",
        min: '0',
        max: '5',
        placeholder: "0",
        description: "What is the clinical stage? Select from the dropdown.",
    },
    gleasonPrimary: {
        value: 3,
        initialValue: 3,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Gleason Primary",
        min: '3',
        max: '5',
        placeholder: "0",
        description: "What is the Gleason Primary Score? This ranges from 3-5",
    },
    gleasonSecondary: {
        value: 3,
        initialValue: 3,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Gleason Secondary",
        min: '3',
        max: '5',
        placeholder: "0",
        description: "What is your Gleason Secondary Score? This ranges from 3-5",
    },
    gradeGroup: {
        value: 0,
        initialValue: 0,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Grade Group",
        min: '0',
        max: '5',
        placeholder: "0",
        description: "What is the grade group of the tumor? This ranges from 0-5",
    },
    totalCores: {
        value: 0,
        initialValue: 0,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Total Cores",
        min: '0',
        max: '40',
        placeholder: "0",
        description: "How many cores were taken?",
    },
    coresPositive: {
        value: 0,
        initialValue: 0,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Number Cores Positive",
        min: '0',
        max: '40',
        placeholder: "0",
        description: "How many were deemed positive?",
    },
    coresWithGroup45: {
        value: 0,
        initialValue: 0,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Cores With Group 4 or 5",
        min: '0',
        max: '40',
        placeholder: "0",
        description: "How many cores were labelled as group 4 or 5",
    },
    numCoresGreaterThan50: {
        value: 0,
        initialValue: 0,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Number of Cores > 50%",
        min: '0',
        max: '40',
        placeholder: "0",
        description: "How many cores had more than 50% of ... This can range from 5-40",
    },
    prostateSize: {
        value: 10,
        initialValue: 10,
        type: "number",
        validation: {
            touched: false,
            error: "",
            msg: "",
        },
        label: "Prostate Size",
        min: '10',
        max: '200',
        placeholder: "10",
        description: "What is the size of the prostate?",
    }
}